os: linux
dist: bionic
language: bash

services:
    - docker

branches:
    only:
        - master
        - dev

stages:
    - name: test
    - name: push_docker
      if: branch = master
    - name: deploy
      if: branch = master

before_install:
    - echo "Installing pre-dependencies ..."

install:
    - echo "Installing dependencies ..."

before_script:
    - echo "Building Docker Image ..."

jobs:
    include:
        - name: "Testing"
          stage: test
          script: echo "Running Tests ..."

        - name: "Push to Docker Registry"
          stage: push_docker
          script: echo "Pushing to Docker Hub ..." 

        - name: "Deploy"
          stage: deploy
          script: echo "Preparing to Deploy ..." 
          before_deploy: echo "Pre-Deploy Commands ..."
          deploy:
              skip-cleanup: true
              script: echo "Actually Deploying ..."
          after_deploy: echo "Post-Deploy Commands ..."

