os: linux
dist: bionic
language: bash

branches:
    only:
        - master
        - dev

stages:
    - name: test
    - name: deploy
      if: branch = master
    - name: push_docker
      if: branch = master

before_install:
    - echo "Installing pre-dependencies ..."

install:
    - echo "Installing dependencies ..."

before_script:
    - echo "Building Docker Image ..."

jobs:
    include:
        - name: "Testing"
          stage: test
          script: echo "Running Tests ..."

        - name: "Deploy"
          stage: deploy
          script: echo "Deploying ..." 

        - name: "Pushing to Docker Registry"
          stage: push_docker
          script: echo "Pushing to Docker Hub ..." 

