os: linux
dist: bionic
language: bash

services:
    - docker

branches:
    only:
        - master
        - dev

stages:
    - name: test
    - name: push_docker
    - name: deploy

before_install:
    - echo "Dependencies pre-installation commands ..."

install:
    - echo "Dependencies Installation commands ..."

before_script:
    - echo "Docker Image Build (From code) commands ..."

jobs:
    include:
        - name: "Testing"
          stage: test
          script:
              - echo "Docker run commands ..."
              - echo "Test Run Commands ..."

        - name: "Push to Docker Registry"
          stage: push_docker
          script: echo "Push-to-Docker-Registry Commands ..." 

        - name: "Deploy"
          stage: deploy
          script: echo "Preparing to Deploy ..." 
          before_deploy: echo "Pre-Deploy Commands ..."
          deploy:
              provider: script
              script: bash scripts/deploy.sh
          after_deploy: echo "Post-Deploy Commands ..."

after_script:
    - echo "At Last, final commands ..."
