language: python
python:
    - '3.4'
    - '3.6'
    - '3.8'

stages:
    - test
    - name: deploy

jobs:
    include:
        - name: "Job1"
          stage: test
          python: '3.8'
          script: echo "Heyo, from test, Job1"

        - name: "Job3"
          stage: test
          script: echo "Heyo, from test, Job3"

        - name: "Job2"
          stage: deploy
          script: echo "Heyo, from deploy, Job2"

